[package]
name = "rust-system-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.24"
crossterm = "0.27"
sysinfo = "0.30"
tokio = { version = "1.0", features = ["full"] }
clap = { version = "4.0", features = ["derive"] }
chrono = "0.4"
anyhow = "1.0"